export const MESSAGES = {
    NOT_CARD_NUMBER: "NO SE ENCONTRO CAMPO NUMERO DE TARJETA",
    NOT_CVV: "NO SE ENCONTRO CAMPO CVV",
    NOT_EXPIRATION_MONTH: "NO SE ENCONTRO CAMPO MES",
    NOT_EXPIRATION_YEAR: "NO SE ENCONTRO CAMPO AÑO DE EXPIRACION",
    NOT_EMAIL: "NO SE ENCONTRO CAMPO EMAIL",
    NOT_ID_COMMERCE: "NO SE ENCONTRO HEADER IDENTIFICADOR DE COMERCIO",
    CARD_NUMBER_INVALID: "FORMATO DE NUMERO DE TARJETA INVALIDO",
    CVV_INVALID: "FROMATO CVV INVALIDO",
    EXPIRATION_MONTH_INVALID: "FORMATO DE MES INVALIDO",
    EXPIRATION_YEAR_INVALID: "FORMATO AÑO DE EXPIRACION INVALIDO",
    EMAIL_INVALID: "FORMATO DE EMAIL INVALIDO",
    ID_COMMERCE_INVALID: "FORMATO DE HEADER IDENTIFICADOR DE COMERCIO INVALIDO",
    OK: 'OK',
    FAIL: 'ERROR INTERNO DEL SERVIDOR',
    ID_COMMERCE_NOTFOUND: "NO SE ENCONTRO IDENTIFICADOR DE COMERCIO",
    BEARER_TOKEN_NOTFOUND: "NOSE SE ENCONTRO BEARER TOKEN"
}

export const COMMERCE = {
    PREFIX_ID: 'pk_test_'
}

export const JWT = {
    error: {
        error_signature: 'invalid signature',
        error_expire: 'jwt expired',
        error_token_null: 'jwt must be provided',
    },
    message: {
        TOKEN_NOT_SPECIFY: 'NO SE PROVISIONO NINGUN TOKEN',
        TOKEN_INVALID: 'TOKEN INVALIDO',
        TOKEN_EXPIRE: 'TOKEN EXPIRO',
        CREDS_NOT_FOUND: 'NO SE PUDO ENCONTRAR CREDENCIALES JWT EN',
        CREDS_NOT_SPECIFY: 'NO SE ESPECIFICO RUTA DE CREDENCIALES JWT',
    },
}